project_id = "kafsqolkxnrsjddjkhyc"

[functions.hubspot-oauth-callback]
verify_jwt = false

[functions.hubspot-get-deal]
verify_jwt = false

[functions.dealer-account-get]
verify_jwt = false

[functions.dealer-account-save]
verify_jwt = false
